TED enabled/disabled selectable
nttcom/pola pull request #21
Opened 2022-09-28 12:59 UTC by Motok1

TED can be enabled/disabled.

if ted is disable, then ted table is null and `pola ted` command is not available.

- ted enable

polad config example
```yaml
global:
  pcep:
    address: **
    port: 4189
  grpc-server:
    address: "127.0.0.1"
    port: 50052
  log:
    path: "/var/log/pola/"
    name: "polad.log"
  ted:
    enable: true
    update-tool: "gobgp"
  gobgp:
    grpc-client:
      address: "127.0.0.1"
      port: 50051
```
 `pola ted` output 
```
user@pola:~$ pola ted
Node: 1
  0000.0aff.0002
  Hostname: ***
  ISIS Area ID: ***
(snip)
```

- ted disable

polad config example
```yaml
global:
  pcep:
    address: **
    port: 4189
  grpc-server:
    address: "127.0.0.1"
    port: 50052
  log:
    path: "/var/log/pola/"
    name: "polad.log"
  ted:
    enable: false
```
 `pola ted` output 
```
user@pola:~$ pola ted
TED is disable by polad
```

2022-09-29 04:06 UTC, Motok1 commented on cmd/pola/ted.go
> +		fmt.Printf("TED is disable by polad\n")
```suggestion
		fmt.Printf("TED is disabled by polad\n")
```

2022-09-29 08:51 UTC, watal requested changes
Please change the variable names as commented. Also, there is an example configuration in ["docs/sources/getting-started.md"](https://github.com/nttcom/pola/blob/main/docs/sources/getting-started.md), please modify that as well.

2022-09-29 08:51 UTC, watal commented on configs/polad.yaml.sample
> +    update-tool: "gobgp"
The name "update-tool" feels like you need to use a tool to get the TED, so names like "input", "source", or "bgp-daemon" might be better.

2022-09-29 08:51 UTC, watal commented on examples/sr-mpls_l3vpn/polad/polad.yaml
> +  grpc-server:
Please rename "update-tool".

2022-09-29 08:51 UTC, watal commented on internal/config/config.go
> +	UpdateTool string `yaml:"update-tool"`
Please rename "update-tool".

2022-10-01 01:49 UTC, watal approved these changes
I have added two comments, please correct them.

2022-10-01 01:49 UTC, watal commented on configs/polad.yaml.sample
> +    update-tool: "gobgp"
```suggestion
    source: "gobgp"
```

2022-10-01 01:49 UTC, watal commented on docs/sources/getting-started.md
> +
Remove blank lines

2022-10-01 11:34 UTC, merged