Feature/add pc err and close
nttcom/pola pull request #66
Opened 2023-03-01 07:00 UTC by Motok1

## Description

### For Users
- Parse PCErr/Close Messages 
- Add Pola Command for close of PCEP session
  - How to use: See [here](https://github.com/nttcom/pola/blob/258470bd8dbfed53ab7876d62dbf8283b5ca65c4/cmd/pola/README.md#pola-session-del-address--j)

### For Developers
- Add Close Object/Message
- Add PCErr Object/Message 
- Changed the structure of the proto file
  - Rename "peeraddr" to "session"
  - Rename "SRPolicyStatus" to "RequestStatus"
  - Add Struct of "Session"

## Type of change

* [x] New features
* [ ] Bug fixes 
* [x] Refactoring
* [ ] Documentation updates

## Motivation and Context

- Understand PCEP error content from polad logs
- Enables session close/restart

2023-03-01 10:06 UTC, watal requested changes
Thanks!!
Please make some corrections.

2023-03-01 10:06 UTC, watal commented on cmd/pola/session_del.go
> +		fmt.Printf("{\"status\": \"success\"}\n")
```suggestion
		fmt.Println("{\"status\": \"success\"}")
```

2023-03-01 10:06 UTC, watal commented on cmd/pola/session_del.go
> +		fmt.Printf("success!\n")
```suggestion
		fmt.Println("success!")
```

2023-03-01 10:06 UTC, watal commented on api/grpc/pola.pb.go
> +// 	protoc        v3.6.1
protoc >= v3.21.12.

2023-03-01 10:06 UTC, watal commented on pkg/packet/pcep/message.go
> +	if err != nil {
Consistent with line 149.

```suggestion
	if err := pcepErrorObject.DecodeFromBytes(messageBody[COMMON_OBJECT_HEADER_LENGTH:commonObjectHeader.ObjectLength]); err != nil { 
```

2023-03-01 10:06 UTC, watal commented on pkg/packet/pcep/message.go
> +	if err != nil {
Consistent with line 188.

```suggestion
	if err := closeObject.DecodeFromBytes(messageBody[COMMON_OBJECT_HEADER_LENGTH:commonObjectHeader.ObjectLength]); err != nil { 
```

2023-03-01 10:06 UTC, watal commented on cmd/pola/session_del.go
> +	sessionDelCmd := &cobra.Command{
```suggestion
	sessionDelCmd := &cobra.Command{
```

2023-03-02 00:32 UTC, Motok1 commented on cmd/pola/session_del.go
> +		fmt.Printf("success!\n")
This modification needs to be applied to many code, so we would like to refactor it in another PR if necessary.

2023-03-02 00:32 UTC, Motok1 commented on cmd/pola/session_del.go
> +		fmt.Printf("{\"status\": \"success\"}\n")
This modification needs to be applied to many code, so we would like to refactor it in another PR if necessary.

2023-03-02 01:31 UTC, watal approved these changes

2023-03-02 01:32 UTC, merged